apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox:stable
          command:
            - sh
            - -c
            - |
              echo "Waiting for Postgres…"
              until nc -z {{ .Values.postgres.host }} {{ .Values.postgres.port }}; do sleep 2; done
              echo "Waiting for Kafka…"
              until nc -z {{ index (splitList "," .Values.kafka.bootstrapServers) 0 }} 9092; do sleep 2; done
      containers:
        - name: order-management
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers }}
