apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-management.fullname" . }}
  labels:
    {{- include "order-management.labels" . | nindent 4 }}
data:
  KAFKA_TOPIC: {{ .Values.kafka.topic | quote }}
