{{- if .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "order-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | quote }}
{{- end }}
{{- if .Values.keycloak.clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.secretName }}
  labels:
    {{- include "order-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ .Values.keycloak.clientSecret | quote }}
{{- end }}
