apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-management.fullname" . }}
  labels:
    {{- include "order-management.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "order-management.selectorLabels" . | nindent 4 }}
