image:
  repository: yourdockerhub/order-management
  tag: latest
replicas: 1
kafka:
  bootstrapServers: localhost:9092
postgres:
  database: orders
  host: postgres
  port: 5432
  username: user
  password: pass
