name: Order Management CI

on:
  push:
    paths:
      - 'Services/Order_Management/order-management/**'
      - '.github/workflows/order-management.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd Services/Order_Management/order-management
          npm ci
      - name: Lint
        run: |
          cd Services/Order_Management/order-management
          npm run lint --if-present
      - name: Test
        run: |
          cd Services/Order_Management/order-management
          npm test --if-present
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/order-management:${{ github.sha }} Services/Order_Management/order-management
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-management:${{ github.sha }}
